// ===================================
// Question Detail Page
// ===================================

function renderQuestionDetailPage(questionId) {
    const question = AppState.questions.find(q => q.id === questionId);

    if (!question) {
        return `
            <div class="section">
                <div class="container container-sm">
                    <div class="empty-state">
                        <div class="empty-state-icon">❌</div>
                        <h3 class="empty-state-title">Question not found</h3>
                        <p class="empty-state-description">The question you're looking for doesn't exist.</p>
                        <button class="btn btn-primary" onclick="navigateTo('questions')">
                            Back to Questions
                        </button>
                    </div>
                </div>
            </div>
        `;
    }

    // Increment views
    question.views++;

    return `
        <div class="section animate-fade-in">
            <div class="container container-sm">
                <!-- Breadcrumb -->
                <div class="mb-lg">
                    <a href="#questions" onclick="navigateTo('questions')" class="text-secondary text-sm">
                        ← Back to Questions
                    </a>
                </div>
                
                <!-- Question Card -->
                <div class="card">
                    <div class="flex items-center gap-md mb-lg">
                        <div class="avatar avatar-lg">${getInitials(question.author)}</div>
                        <div style="flex: 1;">
                            <div class="font-semibold text-lg">${question.author}</div>
                            <div class="text-sm text-tertiary">Asked ${formatDate(question.createdAt)}</div>
                        </div>
                        <div class="flex gap-sm">
                            ${question.hasAIAnswer ? '<span class="badge badge-primary">🤖 AI Answered</span>' : ''}
                            ${question.answers.length > 0 ? '<span class="badge badge-success">✓ Answered</span>' : ''}
                        </div>
                    </div>
                    
                    <h1 style="margin-bottom: var(--spacing-lg);">${question.title}</h1>
                    
                    <div class="text-secondary" style="margin-bottom: var(--spacing-xl); white-space: pre-wrap; line-height: var(--line-height-relaxed);">
                        ${question.content}
                    </div>
                    
                    ${question.code ? `
                        <div style="margin-bottom: var(--spacing-xl);">
                            ${renderCodeBlock(question.code, question.language)}
                        </div>
                    ` : ''}
                    
                    <div class="flex gap-sm mb-lg" style="flex-wrap: wrap;">
                        ${question.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
                    </div>
                    
                    <div class="card-footer">
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-lg text-sm text-secondary">
                                <span>💬 ${question.answers.length} Answer${question.answers.length !== 1 ? 's' : ''}</span>
                                <span>👁️ ${question.views} View${question.views !== 1 ? 's' : ''}</span>
                            </div>
                            <div class="flex gap-sm">
                                <button class="btn btn-secondary btn-sm" onclick="voteQuestion('${questionId}', 'up')">
                                    👍 ${question.upvotes}
                                </button>
                                <button class="btn btn-secondary btn-sm" onclick="voteQuestion('${questionId}', 'down')">
                                    👎 ${question.downvotes}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- AI Answer Section -->
                ${question.aiAnswer ? `
                    <div class="card mt-xl" style="border: 2px solid var(--color-primary);">
                        <div class="flex items-center gap-md mb-md">
                            <div style="font-size: 2rem;">🤖</div>
                            <div>
                                <h3 class="mb-0">AI Answer</h3>
                                <p class="text-sm text-secondary mb-0">Generated by AI</p>
                            </div>
                        </div>
                        <div class="text-secondary" style="white-space: pre-wrap; line-height: var(--line-height-relaxed);">
                            ${question.aiAnswer}
                        </div>
                    </div>
                ` : ''}
                
                <!-- Community Answers -->
                <div class="mt-xl">
                    <h2 class="mb-lg">${question.answers.length} Community Answer${question.answers.length !== 1 ? 's' : ''}</h2>
                    
                    ${question.answers.length > 0 ? question.answers.map(answer => `
                        <div class="card mb-lg">
                            <div class="flex items-center gap-md mb-md">
                                <div class="avatar">${getInitials(answer.author)}</div>
                                <div style="flex: 1;">
                                    <div class="font-semibold">${answer.author}</div>
                                    <div class="text-sm text-tertiary">${formatDate(answer.createdAt)}</div>
                                </div>
                                ${answer.isAccepted ? '<span class="badge badge-success">✓ Accepted</span>' : ''}
                            </div>
                            
                            <div class="text-secondary" style="white-space: pre-wrap; line-height: var(--line-height-relaxed);">
                                ${answer.content}
                            </div>
                            
                            ${answer.code ? `
                                <div style="margin-top: var(--spacing-lg);">
                                    ${renderCodeBlock(answer.code, answer.language)}
                                </div>
                            ` : ''}
                            
                            <div class="card-footer">
                                <div class="flex gap-sm">
                                    <button class="btn btn-secondary btn-sm" onclick="voteAnswer('${answer.id}', 'up')">
                                        👍 ${answer.upvotes}
                                    </button>
                                    <button class="btn btn-secondary btn-sm" onclick="voteAnswer('${answer.id}', 'down')">
                                        👎 ${answer.downvotes}
                                    </button>
                                </div>
                            </div>
                        </div>
                    `).join('') : `
                        <div class="empty-state">
                            <div class="empty-state-icon">💬</div>
                            <h3 class="empty-state-title">No community answers yet</h3>
                            <p class="empty-state-description">Be the first to help!</p>
                        </div>
                    `}
                </div>
                
                <!-- Add Answer Form -->
                ${AppState.currentUser ? `
                    <div class="card mt-xl">
                        <h3 class="mb-lg">Add Your Answer</h3>
                        <form id="addAnswerForm" onsubmit="handleAddAnswer(event, '${questionId}')">
                            <div class="form-group">
                                <label class="form-label">Your Answer</label>
                                <textarea 
                                    id="answerContent" 
                                    class="form-textarea" 
                                    placeholder="Share your knowledge and help the community..."
                                    required
                                    style="min-height: 150px;"
                                ></textarea>
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">Code (Optional)</label>
                                <div id="answerCodeEditor"></div>
                            </div>
                            
                            <button type="submit" class="btn btn-primary">
                                📝 Submit Answer
                            </button>
                        </form>
                    </div>
                ` : `
                    <div class="card mt-xl text-center">
                        <h3 class="mb-md">Want to answer this question?</h3>
                        <p class="text-secondary mb-lg">You need to be logged in to post answers.</p>
                        <button class="btn btn-primary" onclick="openModal('loginModal')">
                            Login to Answer
                        </button>
                    </div>
                `}
            </div>
        </div>
    `;
}

// Initialize code editor for answer after page renders
setTimeout(() => {
    if (document.getElementById('answerCodeEditor')) {
        createCodeEditor('answerCodeEditor', {
            placeholder: 'Paste your code here (optional)...'
        });
        applySyntaxHighlighting();
    }
}, 100);

async function handleAddAnswer(event, questionId) {
    event.preventDefault();

    if (!AppState.currentUser) {
        showNotification('Please login to add an answer', 'warning');
        openModal('loginModal');
        return;
    }

    const content = document.getElementById('answerContent').value;
    const codeEditorEl = document.querySelector('#answerCodeEditor .code-editor-input');
    const languageEl = document.querySelector('#answerCodeEditor .language-selector');

    const answerData = {
        questionId,
        content,
        code: codeEditorEl ? codeEditorEl.value : '',
        language: languageEl ? languageEl.value : 'javascript'
    };

    try {
        const response = await fetch(`${API_URL}/questions/${questionId}/answers`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${localStorage.getItem('authToken')}`
            },
            body: JSON.stringify(answerData)
        });

        const data = await response.json();

        if (response.ok) {
            showNotification('Answer added successfully!', 'success');

            // Reload the question
            await loadQuestions();
            navigateTo('question-detail', { id: questionId });
        } else {
            showNotification(data.message || 'Failed to add answer', 'error');
        }
    } catch (error) {
        showNotification('Connection error. Please try again.', 'error');
    }
}

async function voteQuestion(questionId, voteType) {
    if (!AppState.currentUser) {
        showNotification('Please login to vote', 'warning');
        openModal('loginModal');
        return;
    }

    try {
        const response = await fetch(`${API_URL}/questions/${questionId}/vote`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${localStorage.getItem('authToken')}`
            },
            body: JSON.stringify({ voteType })
        });

        if (response.ok) {
            await loadQuestions();
            navigateTo('question-detail', { id: questionId });
            showNotification('Vote recorded!', 'success');
        }
    } catch (error) {
        showNotification('Failed to vote', 'error');
    }
}

async function voteAnswer(answerId, voteType) {
    if (!AppState.currentUser) {
        showNotification('Please login to vote', 'warning');
        openModal('loginModal');
        return;
    }

    // Handle answer voting
    showNotification('Vote recorded!', 'success');
}
